"""add jugador_id to reservas table

Revision ID: 4823b8ef2768
Revises: ab94331117bb
Create Date: 2025-07-31 03:59:00.564293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4823b8ef2768'
down_revision: Union[str, Sequence[str], None] = 'ab94331117bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('jugador_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'jugador_id')
    # ### end Alembic commands ###
