"""add reservas table

Revision ID: ab94331117bb
Revises: 94830d9a0f31
Create Date: 2025-07-31 03:42:42.873639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab94331117bb'
down_revision: Union[str, Sequence[str], None] = '94830d9a0f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('cancha_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('jugadores', 'telefono',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jugadores', 'telefono',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('reservas')
    # ### end Alembic commands ###
